# Generated by Django 3.1.5 on 2021-01-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0002_auto_20210127_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='genre',
            field=models.CharField(choices=[('メンズ', 'メンズ'), ('ウィメンズ', 'ウィメンズ'), ('メンズ・ウィメンズ', 'メンズ・ウィメンズ')], max_length=200),
        ),
        migrations.AlterModelTable(
            name='list',
            table='post',
        ),
    ]
