# Generated by Django 3.1.5 on 2021-01-28 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0003_auto_20210127_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='address',
            field=models.CharField(max_length=200, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='list',
            name='genre',
            field=models.CharField(choices=[('メンズ', 'メンズ'), ('ウィメンズ', 'ウィメンズ'), ('メンズ・ウィメンズ', 'メンズ・ウィメンズ')], max_length=200, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='list',
            name='hpurl',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='ホームページURL'),
        ),
        migrations.AlterField(
            model_name='list',
            name='shopname',
            field=models.CharField(max_length=200, verbose_name='店名'),
        ),
        migrations.AlterField(
            model_name='list',
            name='treatbland',
            field=models.CharField(max_length=200, verbose_name='取扱ブランド'),
        ),
        migrations.AlterField(
            model_name='list',
            name='treatused',
            field=models.CharField(choices=[('有', '有'), ('無', '無')], max_length=200, verbose_name='古着の取扱'),
        ),
    ]
