# Generated by Django 3.1.5 on 2021-02-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0006_auto_20210207_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='treatbland',
            field=models.CharField(max_length=200),
        ),
    ]
