# Generated by Django 3.1.5 on 2021-02-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0007_auto_20210211_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatBlands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blandname', models.CharField(max_length=255, verbose_name='ブランド名')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
