# Generated by Django 3.1.5 on 2021-02-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0009_list_treat_bland'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TreatBlands',
            new_name='TreatBrands',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='treatbland',
            new_name='treatbrand',
        ),
        migrations.RenameField(
            model_name='treatbrands',
            old_name='blandname',
            new_name='brandname',
        ),
        migrations.RemoveField(
            model_name='list',
            name='treat_bland',
        ),
        migrations.AddField(
            model_name='list',
            name='treat_brand',
            field=models.ManyToManyField(blank=True, related_name='取扱ブランド', to='shop_list.TreatBrands'),
        ),
    ]
